[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.
"""
body = """
{% if version -%}
## [{{ version }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
## [Unreleased]
{% endif %}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits -%}
- {{ commit.message | upper_first }}
{% endfor %}

{% endfor -%}
"""
trim = true

[git]
conventional_commits = true
filter_commits = true
tag_pattern = "^v[0-9].*$"
sort_commits = "oldest"
commit_preprocessors = [
  { pattern = '^[a-z]+(\\([^)]+\\))?!?:\\s*', replace = "" },
]
commit_parsers = [
  { message = "^release:", skip = true },
  { message = "^feat\\(ci\\)", group = "Continuous Integration" },
  { message = "^ci", group = "Continuous Integration" },
  { message = "^feat", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^doc", group = "Documentation" },
  { message = "^docs", group = "Documentation" },
  { message = "^refactor", group = "Changed" },
  { message = "^perf", group = "Changed" },
  { message = "^test", group = "Tests" },
  { message = "^build", group = "Build" },
  { message = "^chore", group = "Maintenance" },
  { message = ".*", group = "Other" },
]
