[package]
name = "ntag424-pcsc"
version = "0.1.0"
edition = "2024"
authors = ["Jannik Schürg <jannik.schuerg+crates@posteo.de>"]
description = "PC/SC transport implementation for NTAG 424 DNA chips."
repository.workspace = true
license.workspace = true
rust-version = "1.88.0"

[dependencies]
pcsc.workspace = true
ntag424 = { version = "0.1.0-beta2", path = "../ntag424" }
