when:
  - event: push
    branch: main
  - event: pull_request
  - event: manual

variables:
  - &rust_image "rust:latest"
  - &cargo_env
      CARGO_BUILD_JOBS: "4"
      CARGO_TERM_COLOR: "always"

steps:
  clippy-default:
    image: *rust_image
    environment: *cargo_env
    commands:
      - apt-get update
      - apt-get install -y --no-install-recommends pkgconf libpcsclite-dev
      - rustup component add clippy
      - cargo clippy --workspace --locked --all-targets -- -D warnings

  clippy-all-features:
    image: *rust_image
    environment: *cargo_env
    commands:
      - apt-get update
      - apt-get install -y --no-install-recommends pkgconf libpcsclite-dev
      - rustup component add clippy
      - cargo clippy --workspace --locked --all-targets --all-features -- -D warnings

  check-examples:
    image: *rust_image
    environment: *cargo_env
    commands:
      - apt-get update
      - apt-get install -y --no-install-recommends pkgconf libpcsclite-dev
      - cargo check --manifest-path examples/Cargo.toml --locked
